### PR TITLE
Cover bugs fixed by downstreamed AtomVM in tests

### LINKED ISSUE #275: Guards crashes
When second guard is provided or guard `when in [list]` atomvm crashes.

Crashes
```elixir
defmodule NumberChecker do
  def check(x) when is_integer(x) and x > 0 do
    x
  end

end

IO.puts(NumberChecker.check(42))
```

```
AtomVM.mjs:1 Uncaught RuntimeError: memory access out of bounds
    at AtomVM.wasm:0xa4f13
    at AtomVM.wasm:0x8c81e
    at AtomVM.wasm:0x91695
    at invokeEntryPoint (AtomVM.mjs:1:13576)
    at handleMessage (AtomVM.mjs:1:3564)
```

Works fine

```elixir
defmodule NumberChecker do
  def check(x) when is_integer(x) do
    x
  end

end

IO.puts(NumberChecker.check(42))
```

### PR DESCRIPTION
**Pull request by mat-hek**
closes #275, #347, #142, #187

### CODE REVIEW

File: test/support/atomvm.ex [hunk 1]
```diff
@@ -123,7 +124,7 @@ defmodule Popcorn.Support.AtomVM do
         "AVM_RUN_DIR='#{run_dir}' '#{@unix_path}' '#{bundle_path}'"
       else
         # $() suppresses sh error about process signal traps, i.e. when AVM crashes
-        ~s|out=$(AVM_RUN_DIR='#{run_dir}' '#{@unix_path}' '#{bundle_path}' 2>'#{log_path}'); echo "$out"|
+        ~s|AVM_RUN_DIR='#{run_dir}' '#{@unix_path}' '#{bundle_path}' 2>'#{log_path}' 1>'#{out_path}'|
```
Comment (jgonet) [inline test/support/atomvm.ex]: Did you read the comment above? :)

Comment (mat-hek) [reply test/support/atomvm.ex]: nope :P fixed
